name: blackbox
description: A fun game for friends that will bring you closer together

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.4+35

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

  cloud_firestore: 0.12.10+2   # Used to allow cloud firestore functionality
  google_sign_in: 4.0.4     # Used for signing in with Google
  firebase_auth: 0.16.0
  flutter_speed_dial: ^1.2.1
  unicorndial: ^1.1.5
  flutter_launcher_icons: 0.7.2+1 # Used for app icon support
  dots_indicator: ^1.0.0
  observable: ^0.22.2
  auto_size_text: ^2.1.0
  package_info: ^0.4.1        # Used to grab (among other things) the version and build number
  path_provider: ^1.3.0       # Used for file handling
  shared_preferences: 0.5.7+2 # Used for config file handling
  audioplayers: ^0.14.0       # Used to play sounds
  vibration: 1.2.2            # Can make the mobile device vibrate
  store_redirect: ^1.0.2
  firebase_analytics: ^5.0.11 # Used to gather more detailed usage statistics
  avatar_glow: ^1.2.0         #glow around ready button
  url_launcher: ^5.5.2
  progress_indicators: ^0.1.5
  slide_to_confirm: ^0.0.7
  liquid_progress_indicator: ^0.3.2
  outline_material_icons: ^0.1.1



  flutter:
    sdk: flutter
    

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  share: ^0.5.3
  back_button_interceptor: ^4.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "images/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/icon.png
    - images/icon2.png
    - images/icon_transparent.png
    - assets/sounds/loser.wav
    - assets/sounds/winner.wav
    - assets/questions.txt

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: atarian
       fonts:
         - asset: assets/fonts/atarian-system-regular.TTF
         - asset: assets/fonts/atarian-system-Bold.TTF
           weight: 700
         - asset: assets/fonts/atarian-system-Italic.TTF
           weight: 300
  #   
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

